AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"
