AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

# It's common and acceptable to define dev dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# has_more? is clearer than more? for pagination
Naming/PredicatePrefix:
  Enabled: false

# validate!, destroy, update_settings are not predicates
Naming/PredicateMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*'
